######################################################################
#
# File name : _246tb_ex9_tb_wave.do
# Created on: Sat May 17 16:13:50 +0800 2025
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
