# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/github/cpu31/project_1/project_1.cache/wt [current_project]
set_property parent.project_path E:/github/cpu31/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files E:/github/cpu31/test_datas/mips_31_mars_simulate.coe
add_files -quiet e:/github/cpu31/project_1/project_1.srcs/sources_1/ip/imem/imem.dcp
set_property used_in_implementation false [get_files e:/github/cpu31/project_1/project_1.srcs/sources_1/ip/imem/imem.dcp]
read_verilog -library xil_defaultlib {
  E:/github/cpu31/project_1/project_1.srcs/sources_1/new/shamt_ext.v
  E:/github/cpu31/project_1/project_1.srcs/sources_1/new/regfile.v
  E:/github/cpu31/project_1/project_1.srcs/sources_1/new/pc.v
  E:/github/cpu31/project_1/project_1.srcs/sources_1/new/npcmaker.v
  E:/github/cpu31/project_1/project_1.srcs/sources_1/new/mux6.v
  E:/github/cpu31/project_1/project_1.srcs/sources_1/new/mux5.v
  E:/github/cpu31/project_1/project_1.srcs/sources_1/new/mux4.v
  E:/github/cpu31/project_1/project_1.srcs/sources_1/new/mux3.v
  E:/github/cpu31/project_1/project_1.srcs/sources_1/new/mux2.v
  E:/github/cpu31/project_1/project_1.srcs/sources_1/new/mux1.v
  E:/github/cpu31/project_1/project_1.srcs/sources_1/new/Jextend.v
  E:/github/cpu31/project_1/project_1.srcs/sources_1/new/imdt_ext.v
  E:/github/cpu31/project_1/project_1.srcs/sources_1/new/controller.v
  E:/github/cpu31/project_1/project_1.srcs/sources_1/new/ALU.v
  E:/github/cpu31/project_1/project_1.srcs/sources_1/new/DMEM.v
  E:/github/cpu31/project_1/project_1.srcs/sources_1/new/IMEM.v
  E:/github/cpu31/project_1/project_1.srcs/sources_1/new/cpu.v
  E:/github/cpu31/project_1/project_1.srcs/sources_1/new/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/github/cpu31/project_1/project_1.srcs/constrs_1/new/cpu31.xdc
set_property used_in_implementation false [get_files E:/github/cpu31/project_1/project_1.srcs/constrs_1/new/cpu31.xdc]


synth_design -top sccomp_dataflow -part xc7a100tcsg324-1


write_checkpoint -force -noxdef sccomp_dataflow.dcp

catch { report_utilization -file sccomp_dataflow_utilization_synth.rpt -pb sccomp_dataflow_utilization_synth.pb }
