######################################################################
#
# File name : _246tb_ex9_tb_compile.do
# Created on: Sat May 17 16:01:28 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/dist_mem_gen_v8_0_10
vlib msim/xil_defaultlib

vmap dist_mem_gen_v8_0_10 msim/dist_mem_gen_v8_0_10
vmap xil_defaultlib msim/xil_defaultlib

vlog -64 -incr -work dist_mem_gen_v8_0_10  \
"../../../project_1.ip_user_files/ipstatic/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \

vlog -64 -incr -work xil_defaultlib  \
"../../../project_1.srcs/sources_1/ip/imem/sim/imem.v" \
"../../../project_1.srcs/sources_1/new/shamt_ext.v" \
"../../../project_1.srcs/sources_1/new/regfile.v" \
"../../../project_1.srcs/sources_1/new/pc.v" \
"../../../project_1.srcs/sources_1/new/npcmaker.v" \
"../../../project_1.srcs/sources_1/new/mux6.v" \
"../../../project_1.srcs/sources_1/new/mux5.v" \
"../../../project_1.srcs/sources_1/new/mux4.v" \
"../../../project_1.srcs/sources_1/new/mux3.v" \
"../../../project_1.srcs/sources_1/new/mux2.v" \
"../../../project_1.srcs/sources_1/new/mux1.v" \
"../../../project_1.srcs/sources_1/new/Jextend.v" \
"../../../project_1.srcs/sources_1/new/imdt_ext.v" \
"../../../project_1.srcs/sources_1/new/controller.v" \
"../../../project_1.srcs/sources_1/new/ALU.v" \
"../../../project_1.srcs/sources_1/new/DMEM.v" \
"../../../project_1.srcs/sources_1/new/IMEM.v" \
"../../../project_1.srcs/sources_1/new/cpu.v" \
"../../../project_1.srcs/sources_1/new/top.v" \
"../../../project_1.srcs/sim_1/new/top_tb.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

