######################################################################
#
# File name : _246tb_ex9_tb_compile.do
# Created on: Fri May 16 05:23:51 +0800 2025
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/xil_defaultlib

vmap xil_defaultlib msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"_246tb_ex9_tb_time_synth.v" \
"../../../../project_1.srcs/sim_1/new/top_tb.v" \


quit -force

