######################################################################
#
# File name : _246tb_ex9_tb_wave.do
# Created on: Fri May 16 05:23:59 +0800 2025
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
